/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
/**
 * *************************
 */

import com.twilio.sdk.TwilioRestClient;
import com.twilio.sdk.TwilioRestException;
import com.twilio.sdk.TwilioRestResponse;
import com.twilio.sdk.resource.factory.MessageFactory;
import com.twilio.sdk.resource.instance.Message;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import neu.edu.UserInterface.ChatClient;
import org.apache.http.NameValuePair;
import org.apache.http.message.BasicNameValuePair;

/**
 *
 * @author Rajat
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    public final String ACCOUNT_SID = "AC1fa19c67de6c5108275855f38d39370e";
    public final String AUTH_TOKEN = "9511e6b265d4a15df963743a91d1ad07";
    public final String APIVERSION = "2010-04-01";

    /**
     * Creates new form PatientLoginJPanel
     */
    public PatientWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = (PatientOrganization) organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        getTime(account);

       // lblPatientName.setText(account.getPatient().getPatientName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTestResult = new javax.swing.JLabel();
        lblHealthSumm = new javax.swing.JLabel();
        lblEmergency = new javax.swing.JLabel();
        lblAppoint = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        lblMedication = new javax.swing.JLabel();
        lblBilling = new javax.swing.JLabel();
        lblchat = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTestResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PatientWorkArea/TestResult.JPG"))); // NOI18N
        lblTestResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTestResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTestResultMouseClicked(evt);
            }
        });
        jPanel1.add(lblTestResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 16, -1, -1));

        lblHealthSumm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PatientWorkArea/HealthSummary.JPG"))); // NOI18N
        lblHealthSumm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHealthSumm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHealthSummMouseClicked(evt);
            }
        });
        jPanel1.add(lblHealthSumm, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 191, -1, -1));

        lblEmergency.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PatientWorkArea/emergency.JPG"))); // NOI18N
        lblEmergency.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEmergency.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmergencyMouseClicked(evt);
            }
        });
        jPanel1.add(lblEmergency, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 366, -1, -1));

        lblAppoint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PatientWorkArea/Appointment.JPG"))); // NOI18N
        lblAppoint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAppoint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAppointMouseClicked(evt);
            }
        });
        jPanel1.add(lblAppoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 191, -1, -1));

        lblMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PatientWorkArea/message.JPG"))); // NOI18N
        lblMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMessageMouseClicked(evt);
            }
        });
        jPanel1.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 16, -1, -1));

        lblMedication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PatientWorkArea/medication.JPG"))); // NOI18N
        lblMedication.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMedication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMedicationMouseClicked(evt);
            }
        });
        jPanel1.add(lblMedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 16, -1, -1));

        lblBilling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PatientWorkArea/billing.JPG"))); // NOI18N
        lblBilling.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBilling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBillingMouseClicked(evt);
            }
        });
        jPanel1.add(lblBilling, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 191, -1, -1));

        lblchat.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajat\\Desktop\\AEDPROJ\\chat-icon.jpg")); // NOI18N
        lblchat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblchat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblchatMouseClicked(evt);
            }
        });
        jPanel1.add(lblchat, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 367, -1, -1));

        lblPatientName.setFont(new java.awt.Font("Calibri Light", 0, 30)); // NOI18N
        lblPatientName.setForeground(new java.awt.Color(1, 126, 1));
        lblPatientName.setText("<value>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblPatientName)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblPatientName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblEmergencyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmergencyMouseClicked
        // TODO add your handling code here:
        String CallerID = "+16173963544";
        String ToCall = "8578002942";
        String Url = "http://twimlets.com/message?Message%5B0%5D=Hello%20from%20my%20java%20application.&Message%5B1%5D=http%3A%2F%2Fcom.twilio.music.electronica.s3.amazonaws.com%2Fteru_-_110_Downtempo_Electronic_4.mp3";
        /* Instantiate a new Twilio Rest Client */
        TwilioRestClient client = new TwilioRestClient(ACCOUNT_SID, AUTH_TOKEN, null);
        //build map of post parameters
        Map params = new HashMap();
        params.put("From", CallerID);
        params.put("To", ToCall);
        params.put("Url", Url);
        TwilioRestResponse response;
        int dialogButton = JOptionPane.showConfirmDialog(null, "Are you sure you want to place this call?", "WARNING", JOptionPane.YES_NO_OPTION);
        if (dialogButton == JOptionPane.YES_OPTION) {
            try {
                response = client.request("/" + APIVERSION + "/Accounts/" + client.getAccountSid() + "/Calls", "POST", params);
                if (response.isError()) {
                    System.out.println("Error making outgoing call: " + response.getHttpStatus() + "n" + response.getResponseText());
                } else {
                    System.out.println(response.getResponseText());
                }
            } catch (TwilioRestException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_lblEmergencyMouseClicked

    private void lblBillingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBillingMouseClicked
        // TODO add your handling code here:
        PatientBillingJPanel patientBillingJPanel = new PatientBillingJPanel(userProcessContainer, userAccount, enterprise, organization);
        userProcessContainer.add("PatientBillingJPanel", patientBillingJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_lblBillingMouseClicked

    private void lblMedicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMedicationMouseClicked
        // TODO add your handling code here:
        PatientMedicationJPanel patientMedicationJPanel = new PatientMedicationJPanel(userProcessContainer, userAccount, enterprise);
        userProcessContainer.add("PatientMedicationJPanel", patientMedicationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_lblMedicationMouseClicked

    private void lblMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMessageMouseClicked
        try {
            TwilioRestClient client = new TwilioRestClient(ACCOUNT_SID, AUTH_TOKEN);
            // Build a filter for the MessageList
            List<NameValuePair> params = new ArrayList<NameValuePair>();
            params.add(new BasicNameValuePair("Body", "Hey Special Care team !!! Can you Please help me Urgently.?"));
            params.add(new BasicNameValuePair("To", "+18578002942"));
            params.add(new BasicNameValuePair("From", "+16173963544"));
            MessageFactory messageFactory = client.getAccount().getMessageFactory();
            Message message = messageFactory.create(params);
            JOptionPane.showMessageDialog(null, "Message Sent Successfully");
            System.out.println(message.getSid());
        } catch (TwilioRestException e) {
            System.out.println("Exception Caught in Sending Message");
        }

    }//GEN-LAST:event_lblMessageMouseClicked

    private void lblTestResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTestResultMouseClicked
        // TODO add your handling code here:
        PatientTestResultJPanel patientTestResultJPanel = new PatientTestResultJPanel(userProcessContainer, userAccount, enterprise);
        userProcessContainer.add("PatientTestResultJPanel", patientTestResultJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_lblTestResultMouseClicked

    private void lblAppointMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAppointMouseClicked
        // TODO add your handling code here:
        PatientAppointmentJPanel patientAppointmentJPanel = new PatientAppointmentJPanel(userProcessContainer, userAccount, enterprise);
        userProcessContainer.add("PatientAppointmentJPanel", patientAppointmentJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_lblAppointMouseClicked

    private void lblHealthSummMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHealthSummMouseClicked
        // TODO add your handling code here:
        PatientVitalSignJPanel patientVitalSignJPanel = new PatientVitalSignJPanel(userProcessContainer, userAccount, enterprise);
        userProcessContainer.add("PatientVitalSignJPanel", patientVitalSignJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_lblHealthSummMouseClicked

    private void lblchatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblchatMouseClicked
        // TODO add your handling code here:
        String IPServer = "localhost";//InetAddress.getLocalHost().toString();
        String[] arguments = new String[]{IPServer};
        new ChatClient().main(arguments);
    }//GEN-LAST:event_lblchatMouseClicked

    private void getTime(UserAccount account) {
        Date dt = new Date();
        Calendar c = Calendar.getInstance();
        c.setTime(dt);
        int hours = c.get(Calendar.HOUR_OF_DAY);
        int min = c.get(Calendar.MINUTE);

        if (hours >= 1 && hours <= 12) {
            lblPatientName.setText("Good Morning" + " " + account.getPatient().getPatientName());
        } else if (hours >= 12 && hours <= 16) {
            lblPatientName.setText("Good Afternoon" + " " + account.getPatient().getPatientName());
        } else if (hours >= 16 && hours <= 21) {
            lblPatientName.setText("Good Evening" + " " + account.getPatient().getPatientName());
        } else if (hours >= 21 && hours <= 24) {
            lblPatientName.setText("Good Night" + " " + account.getPatient().getPatientName());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAppoint;
    private javax.swing.JLabel lblBilling;
    private javax.swing.JLabel lblEmergency;
    private javax.swing.JLabel lblHealthSumm;
    private javax.swing.JLabel lblMedication;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblTestResult;
    private javax.swing.JLabel lblchat;
    // End of variables declaration//GEN-END:variables
}
