/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.DoctorRole.DoctorPatientSearchJPanel;
import javax.swing.JPanel;
import neu.edu.UserInterface.ChatClient;

/**
 *
 * @author Rajat
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;

    /**
     * Creates new form DoctorWorkAreaJPanel1
     */
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblPatientSearch = new javax.swing.JLabel();
        lblPatientMed = new javax.swing.JLabel();
        lblPatTest = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jSplitPane1.setDividerLocation(150);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblPatientSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/DoctorRole/Searchpatient.png"))); // NOI18N
        lblPatientSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPatientSearchMouseClicked(evt);
            }
        });

        lblPatientMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/DoctorRole/medication.jpg"))); // NOI18N
        lblPatientMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPatientMedMouseClicked(evt);
            }
        });

        lblPatTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/DoctorRole/labtest.png"))); // NOI18N
        lblPatTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPatTestMouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rajat\\Desktop\\AEDPROJ\\chat-icon.jpg")); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPatTest)
                    .addComponent(lblPatientSearch)
                    .addComponent(lblPatientMed))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblPatientSearch)
                .addGap(50, 50, 50)
                .addComponent(lblPatientMed)
                .addGap(50, 50, 50)
                .addComponent(lblPatTest)
                .addGap(50, 50, 50)
                .addComponent(jLabel9)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblPatientSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPatientSearchMouseClicked
        // TODO add your handling code here:
       DoctorPatientSearchJPanel doctorPatientSearchJPanel = new DoctorPatientSearchJPanel(userProcessContainer, userAccount, organization, enterprise);
        jSplitPane1.setRightComponent(doctorPatientSearchJPanel);
    }//GEN-LAST:event_lblPatientSearchMouseClicked

    private void lblPatientMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPatientMedMouseClicked
        // TODO add your handling code here:
        DoctorPatientMedicationJPanel doctorPatientMedicationJPanel = new DoctorPatientMedicationJPanel(userProcessContainer, userAccount, organization, enterprise);
        jSplitPane1.setRightComponent(doctorPatientMedicationJPanel);
        
    }//GEN-LAST:event_lblPatientMedMouseClicked

    private void lblPatTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPatTestMouseClicked
        // TODO add your handling code here:
        DoctorPatientLabRequestJPanel doctorPatientLabRequestJPanel = new DoctorPatientLabRequestJPanel(userProcessContainer, userAccount, organization, enterprise);
        jSplitPane1.setRightComponent(doctorPatientLabRequestJPanel);
    }//GEN-LAST:event_lblPatTestMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        String IPServer = "localhost";//InetAddress.getLocalHost().toString();
        String[] arguments = new String[]{IPServer};
        new ChatClient().main(arguments);
    }//GEN-LAST:event_jLabel9MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblPatTest;
    private javax.swing.JLabel lblPatientMed;
    private javax.swing.JLabel lblPatientSearch;
    // End of variables declaration//GEN-END:variables
}
